prometheus:
  prometheusSpec:
    retention: 24h
    resources:
      requests:
        memory: 400Mi
        cpu: 200m
      limits:
        memory: 800Mi
    serviceMonitorSelectorNilUsesHelmValues: false
  service:
    type: NodePort
    nodePort: 30090

grafana:
  adminPassword: admin1234
  service:
    type: NodePort
    nodePort: 30300
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 400Mi

alertmanager:
  enabled: false

nodeExporter:
  enabled: true

prometheus-node-exporter:
  hostNetwork: true
  hostPID: true

kubeStateMetrics:
  enabled: true