apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
  namespace: shopping-api
data:
  DB_URL: jdbc:mysql://mysql:3306/shopping_dev?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
  JWT_EXPIRATION: "86400000"